PUT  http://localhost:8080/events/1
Content-Type: application/json


{
  "Name": "Estifanos updated",
  "Description": "Test description updated",
  "Location": "Addis Ababa",
  "Datetime": "2025-10-05T00:00:00Z",
  "UserID": 1
}
